  
server:
  port: 8889
  servlet:
    encoding:
      force: true  
dubbo:
  application:
    id: ${spring.application.name}
    name: ${spring.application.name}
    qosEnable: false
  cloud:
    subscribed-services: daas-usercenter
  consumer:
    check: false
    timeout: 10000
    retries: 0
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  provider:
    loadbalance: roundrobin
    retries: 0
    timeout: 60000
    version: 1.0.0
#  scan:
#    base-packages: work.metanet.client.vision
  registry:
    id: ${spring.application.name}-registry
    address: nacos://localhost:8848

#腾讯配置
tencent:
  cloud:
    accessKey: AKID2OZcTBcLxUze5Kf4OUKwTqjRtJUPfTcV
    cos:
      bucketName: devpb-12345678
      region: ap-guangzhou
    secretKey: nYSChvue8MJB3g28B7sS1KNBpDLCnIad
    sms:
      appid: 1400384061
      region: ap-guangzhou
      
spring: 
  #thymeleaf配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB
  resources:
    static-locations: classpath:/static/    
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html 
    mode: HTML
    cache: false     
