  
server:
  port: 8889
  servlet:
    encoding:
      force: true  
dubbo:
  application:
    id: ${spring.application.name}
    name: ${spring.application.name}
    qosEnable: false
  cloud:
    subscribed-services: daas-usercenter, daas-device
  consumer:
    check: false
    timeout: 10000
    retries: 0
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  provider:
    loadbalance: roundrobin
    retries: 0
    timeout: 60000
    version: 1.0.0
#  scan:
#    base-packages: work.metanet.server.usercenter.service.impl, work.metanet.server.service
  registry:
    id: ${spring.application.name}-registry
    address: nacos://localhost:8848
logging: 
  level:
    root: warn
    '[work.metanet.client.user.config]': debug
#腾讯配置
tencent:
  cloud:
    accessKey: XXX
    cos:
      bucketName: bn12345678
      region: ap-guangzhou
    secretKey: YYY
    sms:
      appid: 123456
      region: ap-guangzhou

spring: 
  #thymeleaf配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB
  resources:
    static-locations: classpath:/static/    
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html 
    mode: HTML
    cache: false     
