  
server:
  port: 8807

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
     
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: config,stat,log4j
      initial-size: 5
      max-active: 200
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 5
      pool-prepared-statements: true
      stat-view-servlet:
        allow: '*'
        deny: none
        login-password: admin
        login-username: admin
        reset-enable: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/user_center?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: radar
    
  quartz:
    job-store-type: jdbc
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
            tablePrefix: QRTZ_
          plugin:
            shutdownHook:
              class: org.quartz.plugins.management.ShutdownHookPlugin
              cleanShutdown: 'TRUE'
          scheduler:
            instanceId: AUTO
            instanceName: MetanetClusteredScheduler
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
    startup-delay: 10s
    wait-for-jobs-to-complete-on-shutdown: true
    
  redis:
    database: 1
    host: localhost
    lettuce:
      pool:
        max-active: 30
        max-idle: 30
        max-wait: 10000
        min-idle: 10
    password: radar
    port: 6379
      
dubbo:
#  cloud:
#    subscribed-services: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: work.metanet.payment.service.impl, work.metanet.server.service
  registry:
    address: spring-cloud://localhost

logging:
  level:
    '[work.metanet.payment.repository]': trace
    
